### ISSUE TITLE
Javascript error in Hyva template (Unexpected token ')')

### ISSUE THREAD

**Issue by onlinemusketeers** [yireo/Yireo_Webp2#148]
**Hi Jisse! Thank you 1st of all to use your precious time to look at this. :)** I have added here to this issue because

**I get this js error on the page:  Important to note that this is in a Hyva template.**

Thank you Jisse!

`evaluator.js:81 Uncaught SyntaxError: Unexpected token ')'
    at new AsyncFunction (<anonymous>)
    at evaluator.js:81:20
    at _n (evaluator.js:84:28)
    at hn (evaluator.js:95:16)
    at ct (evaluator.js:46:21)
    at g (evaluator.js:26:12)
    at x-on.js:9:33
    at Function.<anonymous> (clone.js:8:57)
    at r (directives.js:78:88)
    at n (directives.js:83:62)`

` Expression: "fullscreen = true; $nextTick(() = loading="
 <img :alt=​"image.caption || 'Lion\u0027s\u0020Mane\u0020Hericium\u0020erinaceus\u0020Powder\u0020\u007C\u0020Mushrooms4life\u0020'" :title=​"image.caption || 'Lion\u0027s\u0020Mane\u0020Hericium\u0020erinaceus\u0020Powder\u0020\u007C\u0020Mushrooms4life\u0020'" @click=​"fullscreen = true;​ $nextTick(()​ = loading=" lazy" alt=​"Lion's Mane Hericium erinaceus Powder | Mushrooms4life" title=​"Lion's Mane Hericium erinaceus Powder | Mushrooms4life">​
J @ error.js:12
`

What browser - **Google Chrome on Windows 11**
Magento version? - **2.4.4**
PHP version? **7.4**
Did you make sure to use composer to install all dependencies? **yes**
 
Which specific composer version of the Yireo WebP2 extension did you install? **0.12.5**
Which specific composer version of the Yireo NextGenImages extension did you install? **0.4.0**
Have you tested this after flushing all caches, especially the Full Page Cache? **yes**
Have you tested this after disabling all caches, especially the Full Page Cache? **yes**
Are you testing this in the Developer Mode or in the Production Mode? **Dev mode**
 
 

Preferably post a screenshot with the settings.

Could you please supply a snapshot of the HTML source of a product page? >>

----------- related HTML ---------------

<div class="relative mb-6"> 
                                

<img
    alt="main product photo"
    title="Lion&#x27;s&#x20;Mane&#x20;Hericium&#x20;erinaceus&#x20;Powder&#x20;&#x7C;&#x20;Mushrooms4life&#x20;"
    class="object-contain object-center w-full h-auto max-h-screen-75 test"
    :class="'opacity-0'"
    src="https://domain.com/media/catalog/product/cache/3b4f390f88ae9f85403f7fc4a463b87b/1/5/1584-lions-mane-paddenstoelen-poeder-bio-mushooms4life.jpg"
    width="700"
    height="700"
    
    @click="fullscreen = true; $nextTick(() => calcPageSize())"
/>

<template x-for="(image, index) in images" :key="index">
    
<picture>
<source type="image/webp" :srcset="fullscreen ? image.full_webp : image.img_webp">
<source type="" :srcset="fullscreen ? image.full : image.img">
<img
        :alt="image.caption || 'Lion\u0027s\u0020Mane\u0020Hericium\u0020erinaceus\u0020Powder\u0020\u007C\u0020Mushrooms4life\u0020'"
        :title="image.caption || 'Lion\u0027s\u0020Mane\u0020Hericium\u0020erinaceus\u0020Powder\u0020\u007C\u0020Mushrooms4life\u0020'"
        @click="fullscreen = true; $nextTick(() = loading="lazy" ></picture>
</template>
<div class="absolute inset-0 hidden w-full h-full bg-white nonmobile"
     :class="{ 'hidden': activeVideoType !== 'youtube' }"
     x-transition.opacity.duration.500ms x-show="
         images[active].type === 'video' && activeVideoType === 'youtube'
     "
>
    <div id="youtube-player" class="w-full h-full"></div>
</div>
<div class="absolute inset-0 hidden w-full h-full bg-white"
     :class="{ 'hidden': activeVideoType !== 'vimeo' }"
     x-transition.opacity.duration.500ms x-show="
         images[active].type === 'video' && activeVideoType === 'vimeo'
     "
>
    <div id="vimeo-player" class="w-full h-full"></div>
</div>
</div>
</div>
<div @resize.window.debounce="calcPageSize(); $nextTick(() => calcActive())">
<div
id="thumbs"
class="flex items-center"
:class="{ 'fixed justify-center bottom-0 left-0 right-0 mx-6': fullscreen }"
style="min-height: 100px;"
>
<button
    aria-label="Previous"
    tabindex="-1"
    class="mr-4 text-black rounded-full outline-none focus:outline-none flex-none"
    :class="{ 'opacity-25 pointer-events-none' : activeSlide === 0, 'hidden' : !isSlider }"
    @click="scrollPrevious"
><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="24" height="24">
<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/>
</svg>
</button>
<div class="js_thumbs_slides thumbs-wrapper relative flex flex-nowrap w-full overflow-auto js_slides snap md:px-1 xl:px-2"
     x-ref="jsThumbSlides"
     @scroll.debounce="calcPageSize(); calcActive()"
>
    <template x-for="(image, index) in images" :key="index">
        <div class="js_thumbs_slide flex shrink-0 mb-2 mr-2 lg:mr-4 last:mr-0">
            <a href="#" @click.prevent="setActive(index);"
               class="block border border-gray-300 hover:border-primary focus:border-primary"
               :class="{'border-primary': active === index}"
            >
                
<picture>
<source type="image/webp" :srcset="image.thumb_webp">
<source type="" :srcset="image.thumb">
<img :src="image.thumb"
                     :alt="image.caption || 'Lion\u0027s\u0020Mane\u0020Hericium\u0020erinaceus\u0020Powder\u0020\u007C\u0020Mushrooms4life\u0020'"
                     :title="image.caption || 'Lion\u0027s\u0020Mane\u0020Hericium\u0020erinaceus\u0020Powder\u0020\u007C\u0020Mushrooms4life\u0020'"
                     width="90"
                     height="90"
                 loading="lazy" /></picture>
</a>
        </div>
    </template>
</div>
<button
    aria-label="Next"
    tabindex="-1"
    class="ml-4 text-black rounded-full outline-none focus:outline-none flex-none"
    :class="{ 'opacity-25 pointer-events-none' : activeSlide >= itemCount-pageSize, 'hidden' : !isSlider }"
    @click="scrollNext"
><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="24" height="24">
<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
</svg>
</button>
</div>
</div>
</div>
</div>
<script>
function initGallery () {
return {
"active": 0,
"videoData": {},
"activeVideoType": false,
"autoplayVideo": false,
"loopVideo": true,
"relatedVideos": false,
"vimeoPlayer": null,
"fullscreen": false,
"isSlider": false,
"initialImages": [{"thumb":"https:\/\/domain.com\/media\/catalog\/product\/cache\/d52308c8e4cdb7e6fcc9224d51687dc6\/1\/5\/1584-lions-mane-paddenstoelen-poeder-bio-mushooms4life.jpg","img":"https:\/\/domain.com\/media\/catalog\/product\/cache\/3b4f390f88ae9f85403f7fc4a463b87b\/1\/5\/1584-lions-mane-paddenstoelen-poeder-bio-mushooms4life.jpg","full":"https:\/\/domain.com\/media\/catalog\/product\/cache\/353f57a88fd5d35febada40be1487b70\/1\/5\/1584-lions-mane-paddenstoelen-poeder-bio-mushooms4life.jpg","caption":"Lion's Mane Hericium erinaceus Powder | Mushrooms4life","position":"2","isMain":true,"type":"image","videoUrl":null,"thumb_webp":"https:\/\/domain.com\/media\/catalog\/product\/cache\/d52308c8e4cdb7e6fcc9224d51687dc6\/1\/5\/1584-lions-mane-paddenstoelen-poeder-bio-mushooms4life.webp","img_webp":"https:\/\/domain.com\/media\/catalog\/product\/cache\/3b4f390f88ae9f85403f7fc4a463b87b\/1\/5\/1584-lions-mane-paddenstoelen-poeder-bio-mushooms4life.webp","full_webp":"https:\/\/domain.com\/media\/catalog\/product\/cache\/353f57a88fd5d35febada40be1487b70\/1\/5\/1584-lions-mane-paddenstoelen-poeder-bio-mushooms4life.webp"}],
"images": [{"thumb":"https:\/\/domain.com\/media\/catalog\/product\/cache\/d52308c8e4cdb7e6fcc9224d51687dc6\/1\/5\/1584-lions-mane-paddenstoelen-poeder-bio-mushooms4life.jpg","img":"https:\/\/domain.com\/media\/catalog\/product\/cache\/3b4f390f88ae9f85403f7fc4a463b87b\/1\/5\/1584-lions-mane-paddenstoelen-poeder-bio-mushooms4life.jpg","full":"https:\/\/domain.com\/media\/catalog\/product\/cache\/353f57a88fd5d35febada40be1487b70\/1\/5\/1584-lions-mane-paddenstoelen-poeder-bio-mushooms4life.jpg","caption":"Lion's Mane Hericium erinaceus Powder | Mushrooms4life","position":"2","isMain":true,"type":"image","videoUrl":null,"thumb_webp":"https:\/\/domain.com\/media\/catalog\/product\/cache\/d52308c8e4cdb7e6fcc9224d51687dc6\/1\/5\/1584-lions-mane-paddenstoelen-poeder-bio-mushooms4life.webp","img_webp":"https:\/\/domain.com\/media\/catalog\/product\/cache\/3b4f390f88ae9f85403f7fc4a463b87b\/1\/5\/1584-lions-mane-paddenstoelen-poeder-bio-mushooms4life.webp","full_webp":"https:\/\/domain.com\/media\/catalog\/product\/cache\/353f57a88fd5d35febada40be1487b70\/1\/5\/1584-lions-mane-paddenstoelen-poeder-bio-mushooms4life.webp"}],
"appendOnReceiveImages": true,
"activeSlide": 0,
"itemCount": 0,
"pageSize": 4,
"pageFillers": 0,
receiveImages(images) {
if (this.appendOnReceiveImages) {
    const initialUrls = this.initialImages.map(image => image.full);
    const newImages = images.filter(image => ! initialUrls.includes(image.full));
    this.images = [].concat(this.initialImages, newImages);
    this.setActive(newImages.length ? this.initialImages.length : 0);
} else {
    this.images = images;
    this.setActive(0);
}
},
resetGallery() {
this.images = this.initialImages;
this.setActive(0);
},
initActive() {
let active = this.images.findIndex(function(image) {
    return image.isMain === true
});
if (active === -1) {
    active = 0;
}
this.setActive(active);
},
setActive(index) {
this.active = index;
if (window.youtubePlayer) {
    window.youtubePlayer.stopVideo();
}
if (this.vimeoPlayer) {
    this.vimeoPlayer.contentWindow.postMessage(JSON.stringify({"method": "pause"}), "*");
}
if (this.images[index].type === 'video') {
    this.activateVideo();
}
},
activateVideo() {
const videoData = this.getVideoData();

if (!videoData) { return }

this.activeVideoType = videoData.type;

if (videoData.type === "youtube") {
    if (!window.youtubePlayer) {
        this.initYoutubeAPI(videoData);
    } else {
        window.youtubePlayer.loadVideoById(videoData.id);
    }

} else if (videoData.type === "vimeo") {
    this.initVimeoVideo(videoData);
}
},
getVideoData() {
const videoUrl = this.images[this.active] && this.images[this.active].videoUrl;

if (!videoUrl) { return }

let id,
    type,
    youtubeRegex,
    vimeoRegex,
    useYoutubeNoCookie = false;

if (videoUrl.match(/youtube\.com|youtu\.be|youtube-nocookie.com/)) {
    id = videoUrl.replace(/^\/(embed\/|v\/)?/, '').replace(/\/.*/, '');
    type = 'youtube';

    youtubeRegex = /^.*(?:(?:youtu\.be\/|v\/|vi\/|u\/\w\/|embed\/)|(?:(?:watch)?\?v(?:i)?=|\&v(?:i)?=))([^#\&\?]*).*/;
    id = videoUrl.match(youtubeRegex)[1];

    if (videoUrl.match(/youtube-nocookie.com/)) {
        useYoutubeNoCookie = true;
    }
} else if (videoUrl.match(/vimeo\.com/)) {
    type = 'vimeo';
    vimeoRegex = new RegExp(['https?:\\/\\/(?:www\\.|player\\.)?vimeo.com\\/(?:channels\\/(?:\\w+\\/)',
        '?|groups\\/([^\\/]*)\\/videos\\/|album\\/(\\d+)\\/video\\/|video\\/|)(\\d+)(?:$|\\/|\\?)'
    ].join(''));
    id = videoUrl.match(vimeoRegex)[3];
}

return id ? {
    id: id, type: type, useYoutubeNoCookie: useYoutubeNoCookie
} : false;
},
initYoutubeAPI(videoData) {
if (document.getElementById('loadYoutubeAPI')) {
    return;
}
const params = {};
const loadYoutubeAPI = document.createElement('script');
loadYoutubeAPI.src = 'https://www.youtube.com/iframe_api';
loadYoutubeAPI.id = 'loadYoutubeAPI';
const firstScriptTag = document.getElementsByTagName('script')[0];
firstScriptTag.parentNode.insertBefore(loadYoutubeAPI, firstScriptTag);

const host = (videoData.useYoutubeNoCookie) ?
    'https://www.youtube-nocookie.com' :
    'https://www.youtube.com';

if (this.autoplayVideo) {
    params.autoplay = this.autoplayVideo;
}
if (!this.relatedVideos) {
    params.rel = 0;
}
const fireYoutubeAPI = document.createElement('script');
fireYoutubeAPI.innerHTML = `function onYouTubeIframeAPIReady() {
    window.youtubePlayer = new YT.Player('youtube-player', {
        host: '${host}',
        videoId: '${videoData.id}',
        playerVars: ${JSON.stringify(params)},
    });
}`;
firstScriptTag.parentNode.insertBefore(fireYoutubeAPI, firstScriptTag);
},
initVimeoVideo(videoData) {
let
    additionalParams = '',
    src;

const timestamp = new Date().getTime();
const vimeoContainer = document.getElementById("vimeo-player");
const videoId = videoData.id;

if (!vimeoContainer || !videoId) return;

if (this.autoplayVideo) {
    additionalParams += '&autoplay=1';
}

if (this.loopVideo) {
    additionalParams += '&loop=1';
}
src = 'https://player.vimeo.com/video/' +
    videoId + '?api=1&player_id=vimeo' +
    videoId +
    timestamp +
    additionalParams;
vimeoContainer.innerHTML =
    `<iframe id="${'vimeo' + videoId + timestamp}"
        src="${src}"
        width="640" height="360"
        webkitallowfullscreen
        mozallowfullscreen
        allowfullscreen
        referrerPolicy="origin"
        allow="autoplay"
        class="object-center w-full h-full object-fit"
     />`;

this.vimeoPlayer = vimeoContainer.childNodes[0];
},
getSlider() {
return this.$refs.jsThumbSlides;
},
calcPageSize() {
const slider = this.getSlider();
if (slider) {
    const slideEl = slider.querySelector('.js_thumbs_slide'),
        marginRight = parseInt(window.getComputedStyle(slideEl).marginRight);

    this.itemCount = slider.querySelectorAll('.js_thumbs_slide').length;
    this.pageSize = Math.round(slider.clientWidth / (slideEl.clientWidth + marginRight));
    this.pageFillers = (
        this.pageSize * Math.ceil(this.itemCount / this.pageSize)
    ) - this.itemCount;

    this.isSlider = ((slider.clientWidth - (this.itemCount * (slideEl.clientWidth + marginRight))) < 0);
}
},
calcActive() {
const slider = this.getSlider();
if (slider) {
    const sliderItems = this.itemCount + this.pageFillers;
    const calculatedActiveSlide = slider.scrollLeft / (slider.scrollWidth / sliderItems);
    this.activeSlide = Math.round(calculatedActiveSlide / this.pageSize) * this.pageSize;
}
},
scrollPrevious() {
this.scrollTo(this.activeSlide - this.pageSize);
},
scrollNext() {
this.scrollTo(this.activeSlide + this.pageSize);
},
scrollTo(idx) {
const slider = this.getSlider();
if (slider) {
    const slideWidth = slider.scrollWidth / (this.itemCount + this.pageFillers);
    slider.scrollLeft = Math.floor(slideWidth) * idx;
    this.activeSlide = idx;
}
},
eventListeners: {
['@keydown.window.escape']() {
    this.fullscreen = false
},
['@update-gallery.window'](event) {
    this.receiveImages(event.detail);
},
['@reset-gallery.window'](event) {
    this.resetGallery();
}
}
}
}
</script>

**Comment by onlinemusketeers** [comment]
I would refer to this to hyva related. see:
https://gitlab.hyva.io/hyva-themes/hyva-compat/magento2-yireo-next-gen-images/-/issues/5
